name: aivideo
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.4
  - ffmpeg
  - pip
  - pip:
      - diffusers[torch]>=0.27.0
      - transformers>=4.42.0
      - accelerate>=0.29.0
      - audiocraft>=1.2.0
      - fastapi>=0.111.0
      - uvicorn[standard]>=0.30.0
      - pydantic>=2.8.0
      - python-dotenv
      - redis>=5.0.0
      - moviepy>=1.0.3
      - opencv-python-headless>=4.11.0.0
      - numpy
      - tqdm
      - typer[all]>=0.12.3
      - httpx>=0.27.0
      - flake8~=7.0
      - pytest~=8.2
      - black~=24.4
